### ISSUE TITLE
angeli exports  systematic IDs with upper case "C"

### ISSUE THREAD

**Issue by ValWood** [dbitton/GLA#1]
I input a list like this
SPAC343.10
SPAC1610.02c
SPAC20H4.03c

but in the "explain" lists, they come out like this
(its a bit of a pin becasue officially it is a lower case "c" and PomBase list upload complains
SPAC343.10
SPAC1610.02C
SPAC20H4.03C
SPAC19G12.15C
SPAC31A2.13C
SPAC664.03
SPAC1D4.11C
SPAPB17E12.04C

**Comment by dbitton** [comment]
Fixed, thanks!
